name: Release Build
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
env:
  SUBWASM_VERSION: 0.16.1
jobs:
  
  native-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: sudo apt -y install protobuf-compiler

      - name: aarch64 setup
        if: contains(matrix.target, 'aarch64')
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib g++-multilib
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

          mkdir -p .cargo
          touch .cargo/config
          printf '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"' >> .cargo/config

      - name: x86_64 setup
        if: contains(matrix.target, 'x86_64')
        run: |
          mkdir -p .cargo
          touch .cargo/config
          printf '[target.x86_64-unknown-linux-gnu]\nrustflags = ["-Clink-arg=-fuse-ld=lld"]' >> .cargo/config

      - name: Install & display rust toolchain
        run: rustup show

      - name: Add aarch64 target
        if: contains(matrix.target, 'aarch64')
        run: rustup target add ${{ matrix.target }}

      - name: Check targets are installed correctly
        run: rustup target list --installed

      - name: Build optimized binary
        run: cargo build --profile production --target ${{ matrix.target }} --locked
